
import "@css/swiper-bundle.min.css";
import "@css/animate.css";
import "@css/bootstrap.min.css";
import "@css/font-awesome.css";
import "@css/magnific-popup.css";
import "@css/meanmenu.css";
import "@css/nice-select.css";
import "@css/main.css";
import type { Metadata } from "next";
import { Chelsea_Market, DM_Sans } from "next/font/google";
import "./globals.css";
import Preloader from "@/layout/Preloader";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-dm-sans",
});
const chelsea_market = Chelsea_Market({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-chelsea_market",
});

export const metadata: Metadata = {
  title: "Danbox - Charity & Fundraiser React NextJS Template",
  description:
    "Generated by danbox - Charity & Fundraiser React NextJS Template",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${chelsea_market.variable} ${dmSans.variable}`}>
        <Preloader />
        {children}
      </body>
    </html>
  );
}
